# Generated by Django 4.2 on 2023-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_citablereference_alter_record_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record1',
            fields=[
                ('id', models.TextField(max_length=355, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('citablereference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
