# Generated by Django 4.2 on 2023-04-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record1',
        ),
    ]
